spring:
  application:
    name: Ar-Application-Service
  datasource:
    name: arApplication-project
    url: jdbc:postgresql://localhost:5432/ar_db
    username: postgres
    password: dragon
    driver-class-name: org.postgresql.Driver
    hikari:
      connectionTimeout : 20000
      idleTimeout: 600000
      maxLifetime: 18000
      maximum-pool-size : 20
      register- mbeans: true
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        show_sql: true
